[variables]
NIXPACKS_INSTALL_PHASE_APT = "curl"

[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = ["dotnet restore", "dotnet build -c Release"]

[phases.start]
cmd = "cd NeedAJobdotCom.Api && dotnet run -c Release --urls http://0.0.0.0:$PORT"